### ISSUE TITLE
(client -> server) pdf 및 이미지 통신 구현

### ISSUE THREAD

**Issue by wavewwave20** [JNU-CAPSTONE-VOCAI/backend#11]
엔드포인트 | /pdf/upload
-- | --
메서드 | POST
요청 형식 | Multipart/form-data
요청 파라미터 | files
최대 파일 개수 | 3
허용 파일 형식 | PDF, JPG, JPEG, PNG, GIF

**Comment by daecheolsong** [comment]
#17
